[package]
name = "wiretray"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "wiretray-settings"
path = "src/bin/wiretray_settings.rs"

[dependencies]
anyhow = "1"

tokio = { version = "1", features = ["full"] }

tracing = "0.1"
tracing-subscriber = "0.3"

ksni = "0.3"
gio = "0.20"

zbus = "4"
uuid = { version = "1", features = ["v4"] }

image = "0.25"
gtk = { version = "0.11.3", package = "gtk4", features = ["v4_12"] }
